export const SET_USER = 'SET_USER';
export const SET_IS_AUTHENTICATED_TRUE = 'SET_IS_AUTHENTICATED_TRUE';
export const SET_IS_AUTHENTICATED_FALSE = 'SET_IS_AUTHENTICATED_FALSE';
export const GET_USER = 'GET_USER';